name: "Expo Example Request"
about: "Suggest an idea for a new Expo example"
issue_body: true
inputs:
  - type: description
    attributes:
      value: "Examples should reflect a single feature or library integration. If the example is too complex i.e. chat app, uber clone, than it's probably better suited for a personal boilerplate or template."
  - type: description
    attributes:
      value: Thanks for taking the time to open a request! Please fill out this form as completely as possible.
  - type: description
    attributes:
      value: If you leave out sections there is a high likelihood your issue will be closed.
  - type: textarea
    attributes:
      label: Summary
      required: true
      description: Describe the example in 1 or 2 sentences
      placeholder: Clearly describe what the example demonstrates and possibly how it differs from existing examples.
  - type: textarea
    attributes:
      label: Any existing examples?
      required: false
      placeholder: Does an example like this already exist?
